FROM node:24-trixie-slim AS build
WORKDIR /samplerate
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  cmake \
  g++ \
  git \
  make \
  python3
COPY . .
RUN npm ci --ignore-scripts
RUN npm run prebuild

FROM scratch
COPY --from=build /samplerate/prebuilds .
