FROM node:22-bookworm-slim AS build
WORKDIR /samplerate
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  cmake \
  g++ \
  git \
  make \
  python3
COPY . .
RUN npm ci --ignore-scripts
RUN MAKEFLAGS=-j$(nproc) npx -y prebuild --backend cmake-js

FROM scratch
COPY --from=build /samplerate/prebuilds .
