FROM node:24-alpine3.22 AS build
WORKDIR /samplerate
RUN apk add \
  ca-certificates \
  cmake \
  g++ \
  git \
  make \
  python3
COPY . .
RUN npm ci --ignore-scripts
RUN npm run prebuild

FROM scratch
COPY --from=build /samplerate/prebuilds .
