name: Build & Test

on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 18, 20, 22 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Add msbuild to PATH
        if: matrix.os == 'windows'
        uses: microsoft/setup-msbuild@v1.3
      - name: Build
        run: |
          npm install --build-from-source
      - name: Test
        if: matrix.os != 'windows-latest'
        run: |
          npm test
        timeout-minutes: 1

  build-and-test-alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20, 22 ]
      fail-fast: false
    container: node:${{ matrix.node }}-alpine
    steps:
      - name: install build deps
        run: |
          apk add ca-certificates cmake g++ git make python3
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install --build-from-source
      - name: Test
        run: |
          npm test
        timeout-minutes: 1
