name: Add native binaries to release

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  prebuild:
    strategy:
      matrix:
        os: [ windows ]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Use nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Add msbuild to PATH
        if: matrix.os == 'windows'
        uses: microsoft/setup-msbuild@v2
      - name: Dependencies
        run: |
          npm install --ignore-scripts
      - name: Build
        shell: bash
        run: |
          npm cache clean --force
          npx -y @audc/prebuild --backend cmake-js
      - name: Upload
        run: |
          npx -y @audc/prebuild --upload-all ${{ secrets.UPLOAD_TOKEN }}
        env:
          MAKEFLAGS: -j4

